name: nkrv_bible
description: 개역개정 성경 앱

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # http 통신
  http: ^0.13.5

  # inner db
  sqflite: ^2.0.0+4
  path: ^1.8.0

  # getX
  get: ^4.6.5

  # logger
  logger: ^1.1.0

  scroll_to_index: ^2.0.0

  # 커스텀 애니메이션
  lottie: ^1.1.0

  # 텍스트 애니메이션
  animated_text_kit: ^4.2.1

  # firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_web_auth: ^0.5.0
  uuid: ^3.0.7

  # google sign in
  google_sign_in: ^5.4.3

  # 페이스북 로그인
  flutter_facebook_auth: ^5.0.7

  dio:
  json_annotation:
  package_info:
  platform:
  shared_preferences:

  flutter_dotenv: ^5.0.2
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner:
  json_serializable:
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  fonts:
    - family: NSRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundOTFB.otf
        - asset: assets/fonts/NanumSquareRoundOTFEB.otf
        - asset: assets/fonts/NanumSquareRoundOTFL.otf
        - asset: assets/fonts/NanumSquareRoundOTFR.otf
  assets:
    - assets/
    - assets/lottie/
    - assets/icon/
    - dev.env